### ISSUE TITLE
How to run demo for this project

### ISSUE THREAD

**Issue by sonnguyen1996** [CopurOnur/ED-MTT#1]
Dear Mr.CopurOnur,

I'm developing a tracking student engagement in an E-learning system for my thesis project. Luckily, I found your work and very interested in it. But I don't know how to run this project for testing purpose such as: using computer's webcam to test, so could you please guide me that how to do that. Have a nice day!

Best regards,

Son Nguyen

**Comment by CopurOnur** [comment]
Hello Son Nguyen,
Thanks for your interest in the project. In this repository, there is no script for real-life experiments. For that, you can refer to the code here,
https://github.com/CopurOnur/Engagement_Detection_OpenFace_Bi-LSTM

but this is not for real-time applications, you can pass a video and get the output video with engagement scores for the frequency you set, for example for each (5 seconds, 10 seconds, etc.). Moreover, the architecture in this repository is not the same as ED-MTT, but you can easily use ED-MTT for this purpose also.  It is possible to make real-time applications by using a webcam but you need to use LSTM or other RNN architecture but not Bi-LSTM since it requires you to have the whole sequence. You can also prefer using frame-level prediction for real-time applications but all these will require a significant amount of adjustment to the code currently available.
